export const FETCHING_USERS_REQUEST = 'FETCHING_USERS_REQUEST';
export const FETCHING_USERS_SUCCESS = 'FETCHING_USERS_SUCCESS';
export const FETCHING_USERS_FAILURE = 'FETCHING_USERS_FAILURE';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SORT_USERS_SUCCESS = 'SORT_USERS_SUCCESS';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_CONNECTION = 'CHANGE_CONNECTION';
export const CANCEL = 'CANCEL';